Trying to use roboelectric.
Using the android gradle plugin 1.1's experimental "unit test"
support, which lets us put unit tests in test/ instead of just
androidTest/, which remains for integration tests.

However, I get this error when trying to run the new test,
after switch the "Test Artifact" to "Unit tests" in the
"Build Versions" tab as in
http://tools.android.com/tech-docs/unit-testing-support
:
java.lang.RuntimeException: Could not find test class. Class: com.murrayc.galaxyzoo.app.ClassifyActivityTest