Activity tests: Set the theme to avoid an exception from AppCompat.
Avoid this exception when using ActivityUnitTestCase:
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.