ClassifyActivity/ClassifyFragment: Avoid IllegalStateException on resume.
Avoid this exception:
  java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState.
caused by us using a FragmentTransaction during onResume().
Instead do it in the parent Activity's onResumeFragments(), where it
is apparently safer. This is very awkward Android API.
However, I cannot reproduce this after experiencing it once,
so it's hard to know if it's really fixed.