ItemsContentProvider.queueRegularTasks(): Use Looper.getMainLooper().
Because I saw this exception once:
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()